test with secrets and manual deployment

diff --git a/.github/workflows/parameters.yml b/.github/workflows/parameters.yml
--- a/.github/workflows/parameters.yml
+++ b/.github/workflows/parameters.yml
@@ -1,48 +1,63 @@
 name: Custom Deploy Workflow
 
 on:
-  push:
-    branches:
-      - dev
   workflow_dispatch:
     inputs:
       source_branch:
         description: 'Source Branch'
         required: true
+        type: string
       target_branch:
         description: 'Target Branch'
         required: true
-      environment:
+        type: string
+      targetEnv:
         description: 'Environment to deploy'
         required: true
+        type: choice
+        default: 'None'
+        options:
+        - None
+        - CI
+        - PRODUCTION
+
+# Environment Variables
+env:
+  PR_NUMBER: ${{ github.event.number }}
+  TARGET_ENVIRONMENT: ${{ inputs.targetEnv }}
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-    - name: Set default inputs
-      run: |
-        echo "SOURCE_BRANCH=${{ github.event.inputs.source_branch || github.ref }}" >> $GITHUB_ENV
-        echo "TARGET_BRANCH=${{ github.event.inputs.target_branch || 'main' }}" >> $GITHUB_ENV
-        echo "ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV
-
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
-        ref: ${{ env.SOURCE_BRANCH }}
+        ref: ${{ github.event.inputs.source_branch }}
         fetch-depth: 0
         token: ${{ env.ACT_LOCAL_TOKEN || secrets.GH_PAT }}
+
+     # check env and branch
+      - name: Check branch and env
+        run: |
+          if [ "${{ env.TARGET_ENVIRONMENT }}" == "CI" ] && [ "${{ inputs.targetBranch }}" != "dev" ]; then
+            echo "::error:: CI environment can only be used with develop"
+            exit 1
+         elif [ "${{ env.TARGET_ENVIRONMENT }}" == "PRODUCTION" ] && [ "${{ inputs.targetBranch }}" != "main" ]; then
+            echo "::error:: PRODUCTION environment can only be used with main branch"
+            exit 1
+          fi
 
     - name: Merge target branch
       run: |
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git config --global user.name "GitHub Actions Bot"
-        git checkout ${{ env.TARGET_BRANCH }}
-        git merge ${{ env.SOURCE_BRANCH }}
-        git push origin ${{ env.TARGET_BRANCH }}
+        git checkout ${{ github.event.inputs.target_branch }}
+        git merge ${{ github.event.inputs.source_branch }}
+        git push origin ${{ github.event.inputs.target_branch }}
 
     - name: Deploy to environment
       run: |
-        echo "Deploying to the ${{ env.ENVIRONMENT }} environment"
+        echo "Deploying to the ${{ github.event.inputs.environment }} environment SECRET=${{secrets.SECRET_TEST}}"
         # Add your deployment commands here based on the selected environment
         # For example, you can use scp, rsync, or a specific deployment tool (e.g. AWS, GCP, etc.)
