zip test

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -77,16 +77,16 @@ jobs:
 
            done
 
-      - name: list `.tar.gz` files
+      - name: list `.zip` files
         run: |
           cd src
-          ls -la *.tar.gz || echo "file not found"
+          ls -la *.zip || echo "file not found"
    
-      - name: Upload all .tar.gz files
+      - name: Upload all .zip files
         uses: actions/upload-artifact@v4
         with:
           name: "${{ github.run_id }}-tar-archives"
-          path: "./src/*.tar.gz"
+          path: "./src/*.zip"
 
 
 
